system:
  env: local
  db-type: ENC(KNHhQH8ZnZOEAt1Zj5RPgaD/AM6cJkuQ9u6yf0/usnUDUmOYm2dk+SdNrjTQ36Y0)
  addr: ENC(WNZWKucdMk0v0E+gQVP8ziKNOFlSuoh2dWXP/elchy/TWeUCcge9PCFXNK+6bgEm)
  use-mongo: ENC(GDzYtVPxSL5F8OPcpeU4AgBw2ePH/K5o8oQezCKhp4DUn/qNfSrImXMcicO0rNnb)
  use-redis: ENC(w5vKebaFKcnyZu5xBTIIPByGtUtjeGrEHTzANf/xgbcgIAdrxxQSoARVmvU8qFcz)

zap:
  level: debug
  prefix: '[github.com/alice52/bili-video-archive]'
  format: json   # console
  director: logs
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

email:
  to: 1252068782@qq.com
  from: zzhang_xz@163.com
  host: smtp.163.com
  secret: ENC(VDPrFqEbvLCyMtQV4SuWXeNuyoGBZOsvBfx4vi/x2lYQIiRrLTwUwkOzboG+T+lu)
  nickname: alice52-bilibi-archive
  port: 465
  is-ssl: true