system:
  env: local
  db-type: mysql
  addr: 8080

zap:
  level: debug
  prefix: '[github.com/alice52/bili-video-archive]'
  format: json   # console
  director: logs
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

email:
  to: 1252068782@qq.com
  from: zzhang_xz@163.com
  host: smtp.163.com
  secret: ENC(Mxw6y2NKApKw9TsIPvbuL3hvuhrTOIrpFQXMxgxF8JzAUZI75Xuqb+jepoFkfXrB)
  nickname: bilibi-archive
  port: 465
  is-ssl: true

mysql:
  port: ENC(U+UIq85Z10ZpmuJjFuC9GSni8WTgeidQq1GIEefC7o0o3Ip9vqvvBYKPGdYV922z)
  config: ""
  db-name: bili_archive
  username: bili
  password: ENC(DrJwohxgMnQ6sUpj8l8EbHV11Y00Ptd9kZc/baaYBDidUnXnOyDPIYBT8CVeAIgZ)
  path: 10.0.4.5
  log-mode: debug
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: true
  migration-path: file://./source/migrations

