name: Build Bilibili Archive

on:
  workflow_dispatch:
  release:
    types: [ released ]
  push:
    branches:
      - master
    paths:
      - 'bili/**'
      - 'common/**'
      - 'netdisc/**'
      - '.github/workflows/build-archive.yml'
  pull_request:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ] # "macOS-latest"
        go: [ '1.19.x', '1.20.x', '1.21.x' ]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version: ${{ matrix.go }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.GOPATH }}/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Build Archive Of Bilibili
        run: |
          MODULE_NAME=bili
          cd $PROJECT_HOME/$MODULE_NAME
          go list -f '{{.Dir}}/...' -m | xargs go build #-o bin/
