name: Build Bilibili Image

on:
  workflow_dispatch:
  release:
    types: [released]
  push:
    branches:
      - master
    paths:
      - '**/github.com/alice52/archive/bilibili/**'
      - '.github/workflows/docker-bilibili.yml'
  pull_request:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] # "macOS-latest"
        go: ['1.18.x', '1.19.x', '1.20.x', '1.21.x']
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, '[image]')"
    env:
      PROJECT_PREFIX: github.com/alice52/archive
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version: ${{ matrix.go }}

      - name: Build Bilibili Archive
        run: |
          PROJECT_NAME=bilibili
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME

      - name: Push Bilibili Docker Image
        run: |

      - name: Build Aliyun Archive
        run: |
          PROJECT_NAME=aliyun
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME

      - name: Push Aliyun Docker Image
        run: |

# push to dockerhub
